name: build

on:
  push:
    branches:
      - release
      - test
jobs:
  build-mac:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Qt 5.15.2
      uses: jurplel/install-qt-action@v2
      with:
        version: "5.15.2"
        modules: "qtwebengine"  
    - name: Install dependencies
      run: |
        brew update
        brew install ninja mpv
    - name: Release build
      run: |
        ./download_webclient.sh
        cd build
        cmake -GNinja -DQTROOT=$Qt5_DIR -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=output ..
        ninja install
    - name: Fix library paths and create dmg
      run: |
        python3 ./scripts/fix-install-names.py ./build/output/Jellyfin\ Media\ Player.app
        brew install create-dmg
        create-dmg --volname "Jellyfin Media Player" --no-internet-enable "JellyfinMediaPlayer.dmg" "./build/output/Jellyfin Media Player.app"
    - name: Archive production artifacts
      uses: actions/upload-artifact@v2
      with:
        name: macos
        path: ${{ github.workspace }}/JellyfinMediaPlayer.dmg